### ISSUE TITLE
Dependency definition with deprecated syntax

### ISSUE THREAD

**Issue by gmerlino** [rahulg/homebrew-hyv#1]
Hi,

brew prints this messages at each step (e.g., update):

Warning: Calling 'depends_on :python3' is deprecated!
Use 'depends_on "python3"' instead.
/usr/local/Homebrew/Library/Taps/rahulg/homebrew-hyv/hyv.rb:8:in `<class:Hyv>'
Please report this to the rahulg/hyv tap!

**Comment by nxusr** [comment]
Fixed in rahulg/homebrew-hyv@e07de89d4be91b746444cf628f7e15f099f9f937
